### ISSUE TITLE
Ctrl+f not working across downsteps in Firefox

### ISSUE THREAD

**Issue by Aquafina-water-bottle** [xythh/hashi#1]
Hey xythh,

Thanks for publishing NotOrange's notes in a much cleaner format! Just wanted to let you know that at least for me, I can't seem to use ctrl+f to search through words that have downsteps. This seems to be a Firefox issue, as it works as expected on Chromium.

For example, searching ばか doesn't highlight anything:
![image](https://user-images.githubusercontent.com/17107540/224532157-593b4e4b-01a1-4cf6-85e1-10db3cea92b3.png)

It seems like the reason why this happens is due to the `:after` rule, and the `content: ""` property. After toggling this off in the inspect element window, the search works properly again.

One potential way to fix this would be to remove the `:after` rule entirely and inserting a 0 text span similarly to how Yomichan exports the pitch accent graph into Anki:
```
<span style="display:inline;"><span style="display:inline-block;position:relative;padding-right:0.1em;margin-right:0.1em;"><span style="display:inline;">よ</span><span style="border-color:currentColor;display:block;user-select:none;pointer-events:none;position:absolute;top:0.1em;left:0;right:0;height:0;border-top-width:0.1em;border-top-style:solid;right:-0.1em;height:0.4em;border-right-width:0.1em;border-right-style:solid;"></span></span><span style="display:inline-block;position:relative;"><span style="display:inline;">む</span><span style="border-color:currentColor;"></span></span></span>
```
(taken from the output of `{pitch-accents}` on 読む).

**Comment by xythh** [comment]
Yep, I was able to reproduce this on firefox-nightly, will try using a 0 text span.

Thank you for the detailed issue.

**Comment by Aquafina-water-bottle** [comment]
The fix worked, thanks for the quick response / fix!

**Comment by xythh** [comment]
Gonna type this up mostly for personal reference or if someone is willing to chime in.

Looking at the way that other sites implement this,most aren't easily searchable.

Yomichan and Kotsu both cannot be CTRL+F through, I'm assuming its due to the use of borders?

using the pseudoelement ::after is the cleanest solution as it works on almost all platforms,is connected correctly and allows searching but does not work on Firefox.

The current solution uses a seperate span and works on all tested platforms(chromium, safari and firefox) but at certain resolutions there is a noticable disconnect/overlap between the right border and the top border, which is especially noticeable on mobile.
![image](https://user-images.githubusercontent.com/121327029/224583127-100cf167-fe27-4746-9f07-e3abb127546b.png)

I'll see if I can come up with something cleaner, going to reopen the issue.

Thank you for the reporting the issue.

**Comment by xythh** [comment]
I found the appropriate solution with some help, it seems that firefox's implementation of ::after and ::before consider content:"" as a valid seperator and does not allowing search over it.

The correct way to implement this which displays properly and allows searching on all browsers is through using css backgrounds as opposed to borders on the spans, this does not require a empty drop-line span, displays properly and is searchable.
